# Generated by Django 3.2.16 on 2022-12-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_myuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_category',
            field=models.IntegerField(choices=[(0, '0+'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], default=0, verbose_name='Возрастная категория'),
        ),
    ]
